### ISSUE TITLE
Precision and balance cache should use multiledger methods

### ISSUE THREAD

**Issue by emschwartz** [interledger/five-bells-connector#139]
Both the precision and balance cache assume they should talk to a `five-bells-ledger`, they should instead use methods on the [multiledger abstraction](https://github.com/interledger/five-bells-connector/blob/master/src/lib/ledgers/multiledger.js)

**Comment by sentientwaffle** [comment]
Fixed by https://github.com/interledger/five-bells-connector/pull/159
