### ISSUE TITLE
Connector should recognize local transfers

### ISSUE THREAD

**Issue by emschwartz** [interledger/five-bells-connector#144]
If you request a quote from a connector from one account to another on the same ledger, right now the connector won't recognize that there is a direct path and it will give you a path from ledger A -> B -> A instead. The connector should (take pity on you and) return a simple transfer object with no nested transfers (and probably no fee)

**Comment by sentientwaffle** [comment]
This will be fixed by https://github.com/interledger/five-bells-connector/pull/150
