### ISSUE TITLE
Use multiledger abstraction for all ledger interactions

### ISSUE THREAD

**Issue by emschwartz** [interledger/five-bells-connector#145]
The connector should be able to interface with multiple different kinds of ledgers. The connector has the [multiledger abstraction](https://github.com/interledger/five-bells-connector/tree/master/src/lib/ledgers), but there are a number of places (e.g. [balanceCache](https://github.com/interledger/five-bells-connector/blob/master/src/lib/balance-cache.js), [testPaymentExpiry](https://github.com/interledger/five-bells-connector/blob/master/src/lib/testPaymentExpiry.js)) where other parts of the code assume the connector is dealing with only `five-bells-ledger`s. All of the functionality necessary for interacting with the ledgers should be moved into the multiledger abstraction and all other parts of the code should use that abstraction layer.

The config will also need to be changed so that the ledger-related options specify which type of ledger they are for.

**Comment by justmoon** [comment]
Fixed by #159
