### ISSUE TITLE
Make Optimistic mode work again

### ISSUE THREAD

**Issue by emschwartz** [interledger/five-bells-connector#153]
In "optimistic" mode, the sender sends a payment with no condition. It is completely up to the connectors to pass on the payment. Honest connectors should.

This used to work in the connector but now it returns a `UnacceptableExpiryError: Destination transfers with execution conditions must have an expires_at field for connector to agree to authorize them`. This is because the `validateExpiry` function assumes that if the payment is a Universal mode payment if it is not an Atomic mode payment. [Here](https://github.com/interledger/five-bells-connector/blob/master/src/models/payments.js#L59-L64) it checks the expiry, but it should not be a problem if there is no expiry set **and** there is no condition set.

**Comment by MatthewPhinney** [comment]
LGTM
