### ISSUE TITLE
Move `ledger` property assignment to plugins and remove `getPrefix`

### ISSUE THREAD

**Issue by justmoon** [interledger/five-bells-connector#198]
Remove this code:

https://github.com/interledger/five-bells-connector/blob/f223d7df1f2cd3820ad318832d5dff3bc6189eb1/src/models/subscriptions.js#L12

https://github.com/interledger/five-bells-connector/blob/f223d7df1f2cd3820ad318832d5dff3bc6189eb1/src/models/subscriptions.js#L21

and make it the responsibility of the plugins to assign the `ledger` property.

**Comment by justmoon** [comment]
Note this change affects at least `ilp-plugin-tests`, `ilp-plugin-bells`, `ilp-plugin-virtual` and `ilp-connector`.

**Comment by sentientwaffle** [comment]
Resolved in https://github.com/interledger/five-bells-connector/pull/202
