### ISSUE TITLE
Quoting: Option to generate complete payment objects

### ISSUE THREAD

**Issue by justmoon** [interledger/five-bells-connector#50]
Even though `source_account` and `destination_account` are not currently needed, it would be nice to be able to provide them, such that the `/quote` endpoint can generate a complete, ready-to-use payment object.

**Comment by justmoon** [comment]
Chatted with @sentientwaffle - this feature could be a security issue. If you enable the connector to build the payment object for you, there is a temptation for you not to double-check it. So a malicious connector could fill themselves in as the destination and if you don't double-check the object you may end up sending the payment and losing money.

This was originally intended to give developer convenience and reduce confusion, because I've seen several people get confused by what that route returns now. So we decided that we will provide a more complete object structually but stop short of filling in the accounts. That way it's obvious where information needs to be added, but it forces users to do so explicitly and not trust the connector to do it.

**Comment by justmoon** [comment]
@sentientwaffle - I still like #51 though. I think it would be nice if everyone but the connector could avoid talking to the ledgers as much as possible. The less we are talking to the ledgers, the less we have to change when we work on supporting other types of ledgers (e.g. Ripple, Bitcoin, Ethereum)

**Comment by justmoon** [comment]
Ok, just to write down the latest discussion. We want the connector to accept the *_account parameters, determine the ledger as per #51, and fill in the ledger field in the transfers. But it should not fill in the account field (even though it could) to force the user to fill it in themselves for safety.

**Comment by justmoon** [comment]
Everyone left and the office is finally quiet. And I'm immediately noticing a lot of things that I missed during the hustle and bustle of the day.

The attack that I was describing does not work. If the connector tampers with the destination, the prepared money will not reach the recipient, they will not sign the receipt and no money will move.

A connector can only deny service in this way, but they can already do that simply by refusing to prepare the destination_transfer. The payment would time out, be retried and the connector penalized by a sophisticated pathfinding engine by having a lower success percentage.

Given that the security concern turned out to be not an issue, I have to go back to the original proposal of having all field fully filled in. Truly sorry for the confusion.

**Comment by emschwartz** [comment]
Actually that's not totally true with the current implementation. Right now it's the last ledger's transfer state receipt that's serving as the `execution_condition`. I know we were planning to deprecate that but it hasn't been done yet and until it is your original attack will work

**Comment by justmoon** [comment]
@emschwartz Yeah, in the RC use case that's not an issue because the receipt is used correctly. I'll make sure that we deprecate the transfer state based receipt. I think having ledgers that can "auto-accept" incoming payments is still useful, but we should redesign the feature so that it is still a meaningful receipt, i.e. "I, ledger XYZ, certify that you have paid X amount to Y account" instead of "I, ledger XYZ, certify that you have done some arbitrary transfer."

**Comment by emschwartz** [comment]
Sounds good
