### ISSUE TITLE
Add persistence to store subscription records

### ISSUE THREAD

**Issue by emschwartz** [interledger/five-bells-connector#91]
While a db is not needed for https://github.com/interledger/five-bells-connector/issues/77, it is needed to ensure that Universal mode connectors do not lose money if the server crashes while waiting for some destination transfers to be executed. The [services/destinationSubscriptions.js](https://github.com/interledger/five-bells-connector/blob/master/src/services/destinationSubscriptions.js#L6) and [services/sourceSubscriptions.js](https://github.com/interledger/five-bells-connector/blob/master/src/services/sourceSubscriptions.js#L3) should use a db rather than an in-memory map.

**Comment by justmoon** [comment]
This is no longer true, we got rid of both reasons for statefulness with nested transfers and the "memo to self".

Closing.
